### PR TITLE
Standardize message timestamp naming

### PR DESCRIPTION
**Pull request by diehuxx**
Taking approach 1 from #406.
> Require all DWN message to have messageTimestamp
dateCreated is a method specific property, ie. in RecordsWrite.
Remove/rename all other variant of date related properties accordingly.

* In `RecordsWrite`, `RecordsDelete`, and `ProtocolsConfigure`: `dateModified` -> `messageTimestamp`.
* `RecordsWrite` retains the `dateCreated` field, which refers to the time that the _record_ was created.
* In `RecordsRead`: `date` -> `messageTimestamp`
* `EventsGet` and `MessagesGet` do not have timestamps of any kind.
* In all other DWN messages, `dateCreated` -> `messageTimestamp`

### CODE REVIEW

**Comment by thehenrytsai** [comment]
@diehuxx, everything looks great, though I think we should also add timestamp for `MessageGet` and `EventGet` to prevent replay. What do you think? Obviously we'd need to add more checks, but that can be done in a future PR.

**Comment by diehuxx** [comment]
> add timestamp for `MessageGet` and `EventGet` to prevent replay

I don't see any reason why not, but not sure if I understand the reason. What do you mean by replay? Also, does the timestamp have any significance if we aren't storing the `MessagesGet` or `EventsGet` messages and we aren't using the timestamp for filtering purposes?

**Comment by thehenrytsai** [comment]
> I don't see any reason why not, but not sure if I understand the reason. What do you mean by replay? Also, does the timestamp have any significance if we aren't storing the `MessagesGet` or `EventsGet` messages and we aren't using the timestamp for filtering purposes?

Imagine if a bad actor got hold of a legit (signed) `MessageGet` message. They can just send this message to a DWN to get the message back any time in the future (assuming no key rotation).

> we aren't using the timestamp for filtering purposes?

Yeah... that's the "we'd need to add more checks, but that can be done in a future PR" part I was referring to, as in, check the timestamp against the current server time, if it's outside of the acceptable "server time drift" range, ignore. This applies to all fetch-type messages that we have including `RecordsQuery` and `RecordsRead`.

**Comment by diehuxx** [comment]
> Imagine if a bad actor got hold of a legit (signed) `MessageGet` message. They can just send this message to a DWN to get the message back any time in the future (assuming no key rotation).

Ahhh okay I see. Thanks for the explanation :). Just pushed a commit adding timestamp to `EventsGet` and `MessagesGet`.

**Review by thehenrytsai — DISMISSED** [review]
🙏

**Review by thehenrytsai — APPROVED** [review]

**Pull request merged**
