### PR TITLE
Exported the test suite in a much cleaner way than 1st attempt

### PR DESCRIPTION
**Pull request by thehenrytsai**
Published an unstable build for testing `0.0.38-unstable-2023-07-13-test-suite-experiment`

### CODE REVIEW

**Comment by mistermoe** [comment]
@thehenrytsai  i can't get vscode intellisense working with sub-package exports _unless_ the "exports" property path matches the exact path of the actual file. e.g.

```json
{
  "exports": {
    ".": {
      "import": "./dist/esm/src/index.js",
      "require": "./dist/cjs/src/index.js",
      "types": "./dist/types/src/index.d.ts"
    },
    "./dist/esm/tests/test-suite": {
      "node": "./dist/esm/tests/test-suite.js",
      "import": "./dist/esm/tests/test-suite.js",
      "types": "./dist/types/tests/test-suite.d.ts"
    },
    "./tests": {
      "node": "./dist/esm/tests/test-suite.js",
      "import": "./dist/esm/tests/test-suite.js",
      "types": "./dist/types/tests/test-suite.d.ts"
    }
  }
}
```

thenn this works

image

Otherwise, when trying with just `/tests`

image

it's worth mentioning that the code itself will run when importing `import { TestSuite } from '@tbd54566975/dwn-sdk-js/tests'`, just no code completion. maybe this has something to do with the `files` property in `package.json`

**Comment by amika-sq** [comment]
@mistermoe Interesting you're not getting code completion. I pulled in the unstable branch into my custom store implementation [here](https://github.com/TBD54566975/dwn-sql-store/blob/amika/dev/tests/test-suite.spec.ts), and it is working for me!

**Comment by mistermoe** [comment]
ok i figured it out. Adding a `jsconfig.json` file to my vanilla js node project with `moduleResolution` set to  _at least_`node16` fixes the issue.

e.g.
```
{
  "compilerOptions": {
    "module": "ESNext",
    "moduleResolution": "nodenext",
    "target": "ES2020",
    "jsx": "react",
    "strictNullChecks": true,
    "strictFunctionTypes": true
  },
  "exclude": [
    "node_modules",
    "**/node_modules/*"
  ]
}
```

image

image

**Comment by mistermoe** [comment]
also confirmed that `import { Dwn } from '@tbd54566975/dwn-sdk-js'` doesn't require you to install `sinon` `ts-sinon` and `chai-as-promised`!

**Review by mistermoe — APPROVED** [review]
🏅

**Pull request merged**
