### PR TITLE
Explicitly export types not referenced by exported types

### LINKED ISSUE #686: Export all types that are referenced by all exported types
Currently there are types referenced by exported types that are not explicitly exported which is not friendly for developers from documentation point of view.

Run `npx typedoc --validation --entryPoints src/index.ts` agains the repo and look for:

```
[warning]... defined in... but not included in the documentation
```

And remove all those instances by exporting the type referenced.

### PR DESCRIPTION
**Pull request by aniketh-varma**
Fixes #686

### CODE REVIEW

**Comment by thehenrytsai** [comment]
This is awesome @aniketh-varma!! Is it possible for you to add the check in `integrity-check.yml` to make sure the job fails if new warnings are introduced going forward (assuming there were no other warnings needing fixing), so that your work is not in vain again.

**Comment by aniketh-varma** [comment]
Hey @thehenrytsai, I do see that the other warnings are still there. This PR addresses only the following warnings-

`[warning]... defined in... but not included in the documentation`

Should I go ahead and a check for only these warnings?

**Comment by aniketh-varma** [comment]
Hi @thehenrytsai, do you have any suggestions for the comment above?

**Comment by LiranCohen** [comment]
Hey @aniketh-varma! I looked at the remaining warnings and maybe those are better suited for a separate PR. I'll approve this one so that we can get it merged in.

**Review by LiranCohen — APPROVED** [review]

**Comment by aniketh-varma** [comment]
Hi @thehenrytsai @taniashiba @LiranCohen, please assign the points label to this PR. Can this be considered as `Medium`? :)

**Comment by taniashiba** [comment]
We're on it, @aniketh-varma !

**Comment by blackgirlbytes** [comment]
Added medium points for you @aniketh-varma !

**Pull request merged**
