### PR TITLE
feat: test coverage increase in ed25519.ts

### LINKED ISSUE #136: Increase code coverage (even if just by a little bit)
### Background:
The code coverage goal is 100% for this repo, so any PR adding any test to increase the overall code coverage would be super useful!

### Task Details:
To know what code hasn't been covered:
1. Run `npm run test:node`
2. Ignore the code coverage summary at the end of the run, there is a better way:
3. Use MacOS Finder or Windows Explorer to open the `coverage/index.html` page, it will show you precisely what line of code is not covered

Files that can be ignored as they will likely be undergoing drastic changes:
- `permissions-request.ts`

## Picking Up This Issue:
- If you'd like to work on this, please comment "picking this up" below, and I'll assign the issue to you 

## Questions:
- If you need assistance or clarification, feel free to comment below.
- Feeling overwhelmed? Join our [`#hack-together` channel](https://discord.gg/tbd) and collaborate with a buddy.
- New to open-source? Check out our [Hacktober `#getting-started` channel](https://discord.gg/tbd).
- [Leaderboard](https://github.com/TBD54566975/developer.tbd.website/issues/721): Check your ranking after finishing this task.

### Resources:
- **Creating a Pull Request**: If you're new to GitHub and unsure how to create a pull request, follow this [step-by-step guide](https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/proposing-changes-to-your-work-with-pull-requests/creating-a-pull-request).

Remember, communication is key! If you have any questions or face any challenges, we're here to help so please don't hesitate to reach out.

Good Luck! 🍁

### PR DESCRIPTION
**Pull request by ANIRUDH-333**
Resolves #136 
Completely covers the `ed25519.ts` file with 100% coverage.

| File Name          | Statements | Branches | Functions | Lines  |
|--------------------|------------|----------|-----------|--------|
| **Before:**        |            |          |           |        |
| All files          |   99.05    |   97.55  |   96.04   |  99.05 |
| ed25519.ts         |   93.1     |   88.88  |   83.33   |  93.1  |
| **After:**         |            |          |           |        |
| All files          |   99.09    |   97.6   |   96.25   |  99.09 |
| ed25519.ts         |   100      |   100    |   100     |  100   |

### CODE REVIEW

**Review by thehenrytsai — APPROVED** [review]
🎖️ 🚀 🙏

**Comment by ANIRUDH-333** [comment]
I can try to fix the lint error but not sure why the 1st one is failing.

**Comment by ANIRUDH-333** [comment]
Fixed the linter issues

**Comment by ANIRUDH-333** [comment]
Hii @mistermoe , @csuwildcat , @thehenrytsai , @LiranCohen. Could you please review this?

**Pull request merged**
